### PR TITLE
Implement handling of update events and progress sync, fix scheduled tasks

### LINKED ISSUE #32: Resume Time Import
According to a user on Chat, the Trakt plug-in/Jellyfin appears to export current play progress,  but does not import it.

Consider this scenario:
* There is a media library, imported to Plex and Jellyfin
* Both servers are connected to Trakt

1) Watch movie to 50% in Jellyfin, synchronize to Trakt. Upon starting playback in Plex, you will resume at 50%.

2) Watch movie to 50% in Plex. Synchronize with Trakt. Upon launching in Jellyfin, it will start at the beginning.

The user would like Jellyfin to resume just as Plex does.

### LINKED ISSUE #34: Removed collections not synced to Trakt
When a movie or TV episode is added to my Jellyfin library, the Trakt plugin marks it as collected in Trakt when syncing. However, when the media file is removed, the plugin won't mark it as uncollected in Trakt. I understand that some people may have more than one media libraries so this may not be a desired feature, but would it be possible to add an option that enables this?

### LINKED ISSUE #35: Wrongly matched shows/movies not updated in Trakt collection
Might be related to https://github.com/jellyfin/jellyfin-plugin-trakt/issues/34#issue-552860421, but in this case it's definitely a bug as the wrong matched items should be removed from the Trakt collection. Also, after fixing the match the correctly matched items are not being added to Trakt collection.

### LINKED ISSUE #36: Removed Plays
I've been having problems where my plays (scrobbles) have been removed from my history, even old ones that had nothing to do with jellyfin. I emailed support at trakt and seemed like the app removing those playthroughs is Jellyfin.

I will be having a look at this, see if I can fix it, but I wanted to open the discussion to see if anyone else was having a look at this or if there were any pointers, as it's my first time with this project, will take me a while to wrap my head around the main project and the plugins.

Seems to be related to #15 and fixed by #17, but this happened to me during Christmas and January. So I will be having a look anyway.

### LINKED ISSUE #47: Watched status being set when new items in excluded folders are imported
I am having an issue with (I believe) the Trakt plugin setting the watched status on newly detected TV shows in folders that are marked as excluded. These _are_ shows that I have watched in Trakt, but I am adding reaction videos to a separate library which I do not want marked as watched on import. This is occurring under the following conditions (using an episode of BtVS as an example):

TV Shows Library - E:\Media\TV Shows
E:\Media\TV Shows\DVDs\Buffy the Vampire Slayer\S02E09 - What's My Line (1).mkv - Marked as watched in Trakt, and status imported into Jellyfin

_Example Reactor_ Library - E:\Media\TV Shows\Reactions\\_Example Reactor_
E:\Media\TV Shows\Reactions\\_Example Reactor_\Buffy the Vampire Slayer\S02E09 - What's My Line (1) - _Example Reactor_ Reaction.mp4

What happens: S02E09 - What's My Line (1) - _Example Reactor_ Reaction.mp4 is marked as watched on import
What should happen: S02E09 - What's My Line (1) - _Example Reactor_ Reaction.mp4 should not be marked as watched

In the Trakt plugin settings, the E:\Media\TV Shows\Reactions\_Example Reactor_ folder is marked as excluded. Skip watched import from Trakt is **not** set.

I have verified that the status is not being taken from the TV Shows Library by using another user which is not configured with a Trakt account - that user does not exhibit the same behaviour.

Jellyfin Server: 10.5.5 (Windows)
Trakt Plugin: 9.0.0.0

### LINKED ISSUE #77: Multi-episode files not marked correctly on Trakt
When watching a multi-episodes file (ie Episodes 20-21 on the same file), the plugin will only mark the second one as watched on Trakt, and the scrobble won't work

### LINKED ISSUE #84: Sync Collections doesn't remove from Trakt collections when its deleted from library
currently when we remove item from library ( from jellyfin itself) it doesn't get removed from trakt collections. Can a option be given to remove from trakt collection too if its deleted from jellyfin library ( or from os folder).

It can be implement during scan also:

1) after trakt sync collection is done
2) remove from trakt collections if it isn't in jellyfin

### PR DESCRIPTION
**Pull request by Shadowghost**
* Remove not properly working `SplittableProgress`
* Implement handling `update` library events
* Implement paused play syncing (syncs playback state between clients when importing playstate)
* Fix handling of watched state syncing when marking an item as watched
* Fix double ` Saved` notification on plugin config save
* Make sure all items residing in excluded folders are removed before syncing
* Add locking to sync queue objects
* Fix error reporting
* Better handle multi-episode files (this may still require more tests)

Fixes #32
Fixes #34
Fixes #35
Fixes #36
Fixes #47
Fixes #77
Fixes #84

### CODE REVIEW

File: Trakt/Api/TraktApi.cs [hunk 1]
```diff
@@ -427,10 +417,11 @@ public async Task<List<TraktScrobbleResponse>> SendEpisodeStatusUpdateAsync(Epis
 
                         if (traktUser.ExportMediaInfo)
                         {
-                            // traktEpisodeCollected.Is3D = episode.Is3D;
                             traktEpisodeCollected.AudioChannels = audioStream.GetAudioChannels();
                             traktEpisodeCollected.Audio = audioStream.GetCodecRepresetation();
                             traktEpisodeCollected.Resolution = episode.GetDefaultVideoStream().GetResolution();
+                            traktEpisodeCollected.Is3D = episode.Is3D;
+                            traktEpisodeCollected.Hdr = episode.GetDefaultVideoStream().GetHdr();
```
Comment (cvium) [inline Trakt/Api/TraktApi.cs:424]: You are calling `GetDefaultVideoStream` twice.

File: Trakt/Extensions.cs [hunk 2]
```diff
@@ -234,26 +247,166 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+        /// <summary>
+        /// Checks if a <see cref="BaseItem"/> matches a <see cref="TraktMovie"/>.
+        /// </summary>
+        /// <param name="item">The <see cref="BaseItem"/>.</param>
+        /// <param name="movie">The <see cref="TraktMovie"/>.</param>
+        /// <returns><see cref="bool"/> indicating if the <see cref="BaseItem"/> matches a <see cref="TraktMovie"/>.</returns>
+        public static bool IsMatch(BaseItem item, TraktMovie movie)
+        {
+            var imdb = item.GetProviderId(MetadataProvider.Imdb);
+            if (!string.IsNullOrWhiteSpace(imdb) && string.Equals(imdb, movie.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:302]: Redundant
```suggestion
            if (string.Equals(imdb, movie.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
```

File: Trakt/Extensions.cs [hunk 3]
```diff
@@ -234,26 +247,166 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+            var tmdb = item.GetProviderId(MetadataProvider.Tmdb);
+            if (!string.IsNullOrWhiteSpace(tmdb) &&
+                string.Equals(tvdb, show.Ids.Tmdb.ToString(), StringComparison.OrdinalIgnoreCase))
+            {
+                return true;
+            }
+
+            var imdb = item.GetProviderId(MetadataProvider.Imdb);
+            if (!string.IsNullOrWhiteSpace(imdb) &&
+                string.Equals(imdb, show.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:340]:
```suggestion
            if (string.Equals(imdb, show.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
```

File: Trakt/Extensions.cs [hunk 4]
```diff
@@ -234,26 +247,166 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+            var tvdb = item.GetProviderId(MetadataProvider.Tvdb);
+            if (!string.IsNullOrWhiteSpace(tvdb) &&
+                string.Equals(tvdb, show.Ids.Tvdb.ToString(), StringComparison.OrdinalIgnoreCase))
+            {
+                return true;
+            }
+
+            var tmdb = item.GetProviderId(MetadataProvider.Tmdb);
+            if (!string.IsNullOrWhiteSpace(tmdb) &&
+                string.Equals(tvdb, show.Ids.Tmdb.ToString(), StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:333]:
```suggestion
            if (string.Equals(tvdb, show.Ids.Tmdb.ToString(CultureInfo.InvariantCulture), StringComparison.OrdinalIgnoreCase))
```

File: Trakt/Extensions.cs [hunk 5]
```diff
@@ -234,26 +247,166 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+        /// Checks if a <see cref="Series"/> matches a <see cref="TraktShow"/>.
+        /// </summary>
+        /// <param name="item">The <see cref="Series"/>.</param>
+        /// <param name="show">The <see cref="TraktShow"/>.</param>
+        /// <returns><see cref="bool"/> indicating if the <see cref="Series"/> matches a <see cref="TraktShow"/>.</returns>
+        public static bool IsMatch(Series item, TraktShow show)
+        {
+            var tvdb = item.GetProviderId(MetadataProvider.Tvdb);
+            if (!string.IsNullOrWhiteSpace(tvdb) &&
+                string.Equals(tvdb, show.Ids.Tvdb.ToString(), StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:326]:
```suggestion
            if (string.Equals(tvdb, show.Ids.Tvdb.ToString(), StringComparison.OrdinalIgnoreCase))
```

File: Trakt/Extensions.cs [hunk 6]
```diff
@@ -234,26 +247,166 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+        public static bool IsMatch(BaseItem item, TraktMovie movie)
+        {
+            var imdb = item.GetProviderId(MetadataProvider.Imdb);
+            if (!string.IsNullOrWhiteSpace(imdb) && string.Equals(imdb, movie.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
+            {
+                return true;
+            }
+
+            var tmdb = item.GetProviderId(MetadataProvider.Tmdb);
+            if (movie.Ids.Tmdb.HasValue && string.Equals(tmdb, movie.Ids.Tmdb.Value.ToString(CultureInfo.InvariantCulture), StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:308]: I would consider changing the type of the IDs to string since we treat them as such

File: Trakt/Extensions.cs [hunk 7]
```diff
@@ -234,26 +247,166 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+                string.Equals(imdb, show.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
+            {
+                return true;
+            }
+
+            return false;
+        }
+
+        /// <summary>
+        /// Removes all <see cref="BaseItem"/>s contained in expluded folders from a <see cref="HashSet{BaseItem}"/>..
```
Comment (cvium) [inline Trakt/Extensions.cs:349]:
```suggestion
        /// Removes all <see cref="BaseItem"/>s contained in excluded folders from a <see cref="HashSet{BaseItem}"/>.
```

File: Trakt/Helpers/LibraryManagerEventsHelper.cs [hunk 8]
```diff
@@ -137,6 +137,21 @@ private async Task OnQueueTimerCallbackInternal()
                     _logger.LogInformation("No movie additions to process");
                 }
 
+                var queuedMovieUpdates = queue.Where(ev =>
+                    new Guid(ev.TraktUser.LinkedMbUserId).Equals(new Guid(traktUser.LinkedMbUserId)) &&
```
Comment (cvium) [inline Trakt/Helpers/LibraryManagerEventsHelper.cs:141]: `new Guid(traktUser.LinkedMbUserId)` is being called a lot. It's just a struct, but it should really be saved in a variable

Comment (cvium) [reply Trakt/Helpers/LibraryManagerEventsHelper.cs:141]: And also, the queue is being iterated quite a few times. Would it not be better to iterate once and add events to separate lists?

File: Trakt/Helpers/LibraryManagerEventsHelper.cs [hunk 9]
```diff
@@ -191,7 +251,9 @@ private async Task ProcessQueuedShowEvents(IEnumerable<LibraryEvent> events, Tra
         {
             var shows = events.Select(lev => (Series)lev.Item)
                 .Where(lev => !string.IsNullOrEmpty(lev.Name) && !string.IsNullOrEmpty(lev.GetProviderId(MetadataProvider.Tvdb)))
-                .ToList();
+                .ToHashSet();
+
+            Extensions.RemoveExcludedItems(shows, traktUser);
```
Comment (cvium) [inline Trakt/Helpers/LibraryManagerEventsHelper.cs:256]: Shouldn't this be a filter for the LINQ Where?

File: Trakt/Helpers/LibraryManagerEventsHelper.cs [hunk 10]
```diff
@@ -251,7 +317,7 @@ private async Task ProcessQueuedEpisodeEvents(IEnumerable<LibraryEvent> events,
             }
 
             var payload = new List<Episode>();
-            var currentSeriesId = episodes[0].Series.Id;
+            var currentSeriesId = episodes.FirstOrDefault().Series.Id;
```
Comment (cvium) [inline Trakt/Helpers/LibraryManagerEventsHelper.cs:320]: Why?
```suggestion
            var currentSeriesId = episodes[0].Series.Id;
```

File: Trakt/Helpers/UserDataManagerEventsHelper.cs [hunk 11]
```diff
@@ -45,7 +45,12 @@ public void ProcessUserDataSaveEventArgs(UserDataSaveEventArgs userDataSaveEvent
 
             if (userPackage == null)
             {
-                _userDataPackages.Add(new UserDataPackage { TraktUser = traktUser });
+                userPackage = new UserDataPackage
+                {
+                    TraktUser = traktUser
+                };
+
+                _userDataPackages.Add(userPackage);
```
Comment (cvium) [inline Trakt/Helpers/UserDataManagerEventsHelper.cs:53]: Seems like an unnecessary change

File: Trakt/Helpers/UserDataManagerEventsHelper.cs [hunk 12]
```diff
@@ -109,29 +114,56 @@ public void ProcessUserDataSaveEventArgs(UserDataSaveEventArgs userDataSaveEvent
...
+                            userPackage.UnSeenEpisodes.ToList(),
+                            userPackage.TraktUser,
+                            false,
+                            CancellationToken.None).ConfigureAwait(false);
+                        userPackage.UnSeenEpisodes.Clear();
+                    }
+
+                    userPackage.CurrentSeriesId = episode.Series.Id;
                 }
+                else
```
Comment (cvium) [inline Trakt/Helpers/UserDataManagerEventsHelper.cs:143]: What is the difference between the if and the else?

File: Trakt/ServerMediator.cs [hunk 13]
```diff
@@ -158,6 +160,28 @@ private void LibraryManagerItemAdded(object sender, ItemChangeEventArgs itemChan
...
+        /// <summary>
+        /// Library item was updated.
+        /// Let trakt.tv know which item was updated in the user's library.
+        /// </summary>
+        /// <param name="sender">The sending entity.</param>
+        /// <param name="itemChangeEventArgs">The <see cref="ItemChangeEventArgs"/>.</param>
+        private void LibraryManagerItemUpdated(object sender, ItemChangeEventArgs itemChangeEventArgs)
+        {
+            // Don't do anything if it's not a supported media type
+            if (!(itemChangeEventArgs.Item is Movie) && !(itemChangeEventArgs.Item is Episode) && !(itemChangeEventArgs.Item is Series))
```
Comment (cvium) [inline Trakt/ServerMediator.cs:172]:
```suggestion
            if (itemChangeEventArgs.Item is not Movie && itemChangeEventArgs.Item is not Episode && itemChangeEventArgs.Item is not Series)
```

File: Trakt/Helpers/UserDataManagerEventsHelper.cs (hunk 12 above)
Comment (Shadowghost) [reply Trakt/Helpers/UserDataManagerEventsHelper.cs:143]: The if triggers when we change the series, the else triggers when we are in the same series and the current queue exceeds 100 items.

File: Trakt/Extensions.cs [hunk 14]
```diff
@@ -299,13 +299,13 @@ public static IEnumerable<TraktMovieCollected> FindMatches(BaseItem item, IEnume
...
             var imdb = item.GetProviderId(MetadataProvider.Imdb);
-            if (!string.IsNullOrWhiteSpace(imdb) && string.Equals(imdb, movie.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
+            if (string.Equals(imdb, movie.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
             {
                 return true;
             }
 
             var tmdb = item.GetProviderId(MetadataProvider.Tmdb);
-            if (movie.Ids.Tmdb.HasValue && string.Equals(tmdb, movie.Ids.Tmdb.Value.ToString(CultureInfo.InvariantCulture), StringComparison.OrdinalIgnoreCase))
+            if (string.Equals(tmdb, movie.Ids.Imdb, StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:308]: should be tmdb

File: Trakt/Extensions.cs [hunk 15]
```diff
@@ -322,91 +322,30 @@ public static bool IsMatch(BaseItem item, TraktMovie movie)
...
-                string.Equals(tvdb, show.Ids.Tvdb.ToString(), StringComparison.OrdinalIgnoreCase))
+            if (string.Equals(tvdb, show.Ids.Tvdb, StringComparison.OrdinalIgnoreCase))
             {
                 return true;
             }
 
             var tmdb = item.GetProviderId(MetadataProvider.Tmdb);
-            if (!string.IsNullOrWhiteSpace(tmdb) &&
-                string.Equals(tvdb, show.Ids.Tmdb.ToString(), StringComparison.OrdinalIgnoreCase))
+            if (string.Equals(tvdb, show.Ids.Tmdb, StringComparison.OrdinalIgnoreCase))
```
Comment (cvium) [inline Trakt/Extensions.cs:331]: should be tmdb

File: Trakt/Helpers/LibraryManagerEventsHelper.cs [hunk 16]
```diff
@@ -107,10 +107,70 @@ private async Task OnQueueTimerCallbackInternal()
...
+                var queuedShowDeletes = new List<LibraryEvent>();
+                var queuedShowAdds = new List<LibraryEvent>();
+                var queuedShowUpdates = new List<LibraryEvent>();
+
+                foreach (var ev in queue)
+                {
+                    var eventTraktUserGuid = new Guid(ev.TraktUser.LinkedMbUserId);
+                    if (eventTraktUserGuid.Equals(traktUserGuid))
+                    {
+                        if (ev.Item is Movie)
```
Comment (cvium) [inline Trakt/Helpers/LibraryManagerEventsHelper.cs:127]: I think this is a little cleaner
```diff
Index: Trakt/Helpers/LibraryManagerEventsHelper.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Trakt/Helpers/LibraryManagerEventsHelper.cs b/Trakt/Helpers/LibraryManagerEventsHelper.cs
--- a/Trakt/Helpers/LibraryManagerEventsHelper.cs	(revision 73dc33dd88616b6f74bff4d99cce22a166dce405)
+++ b/Trakt/Helpers/LibraryManagerEventsHelper.cs	(date 1650572554645)
@@ -124,151 +124,66 @@
                     var eventTraktUserGuid = new Guid(ev.TraktUser.LinkedMbUserId);
                     if (eventTraktUserGuid.Equals(traktUserGuid))
                     {
-                        if (ev.Item is Movie)
+                        switch (ev.Item)
                         {
-                            if (ev.EventType is EventType.Remove)
-                            {
+                            case Movie when ev.EventType is EventType.Remove:
                                 queuedMovieDeletes.Add(ev);
-                            }
-                            else if (ev.EventType is EventType.Add)
-                            {
+                                break;
+                            case Movie when ev.EventType is EventType.Add:
                                 queuedMovieAdds.Add(ev);
-                            }
-                            else if (ev.EventType is EventType.Update)
-                            {
+                                break;
+                            case Movie when ev.EventType is EventType.Update:
                                 queuedMovieUpdates.Add(ev);
-                            }
-                        }
-                        else if (ev.Item is Episode)
-                        {
-                            if (ev.EventType is EventType.Remove)
-                            {
+                                break;
+                            case Episode when ev.EventType is EventType.Remove:
                                 queuedEpisodeDeletes.Add(ev);
-                            }
-                            else if (ev.EventType is EventType.Add)
-                            {
+                                break;
+                            case Episode when ev.EventType is EventType.Add:
                                 queuedEpisodeAdds.Add(ev);
-                            }
-                            else if (ev.EventType is EventType.Update)
-                            {
+                                break;
+                            case Episode when ev.EventType is EventType.Update:
                                 queuedEpisodeUpdates.Add(ev);
-                            }
-                        }
-                        else if (ev.Item is Series)
-                        {
-                            if (ev.EventType is EventType.Remove)
-                            {
+                                break;
+                            case Series when ev.EventType is EventType.Remove:
                                 queuedShowDeletes.Add(ev);
-                            }
-                            else if (ev.EventType is EventType.Add)
-                            {
+                                break;
+                            case Series when ev.EventType is EventType.Add:
                                 queuedShowAdds.Add(ev);
-                            }
-                            else if (ev.EventType is EventType.Update)
-                            {
+                                break;
+                            case Series when ev.EventType is EventType.Update:
                                 queuedShowUpdates.Add(ev);
-                            }
+                                break;
                         }
                     }
                 }
 
-                if (queuedMovieDeletes.Any())
-                {
-                    _logger.LogInformation("{Count} movie deletions to process", queuedMovieDeletes.Count);
-                    await ProcessQueuedMovieEvents(queuedMovieDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No movie deletions to process");
-                }
-
-                if (queuedMovieAdds.Any())
-                {
-                    _logger.LogInformation("{Count} movie additions to process", queuedMovieAdds.Count);
-                    await ProcessQueuedMovieEvents(queuedMovieAdds, traktUser, EventType.Add).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No movie additions to process");
-                }
-
-                if (queuedMovieUpdates.Any())
-                {
-                    _logger.LogInformation("{Count} movie updates to process", queuedMovieUpdates.Count);
-                    await ProcessQueuedMovieEvents(queuedMovieUpdates, traktUser, EventType.Update).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No movie updates to process");
-                }
+                await ProcessQueuedMovieEvents(queuedMovieDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
+                await ProcessQueuedMovieEvents(queuedMovieAdds, traktUser, EventType.Add).ConfigureAwait(false);
+                await ProcessQueuedMovieEvents(queuedMovieUpdates, traktUser, EventType.Update).ConfigureAwait(false);
 
-                if (queuedEpisodeDeletes.Any())
-                {
-                    _logger.LogInformation("{Count} episode deletions to process", queuedEpisodeDeletes.Count);
-                    await ProcessQueuedEpisodeEvents(queuedEpisodeDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No episode deletions to process");
-                }
-
-                if (queuedEpisodeAdds.Any())
-                {
-                    _logger.LogInformation("{Count} episode additions to process", queuedEpisodeAdds.Count);
-                    await ProcessQueuedEpisodeEvents(queuedEpisodeAdds, traktUser, EventType.Add).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No episode additions to process");
-                }
-
-                if (queuedEpisodeUpdates.Any())
-                {
-                    _logger.LogInformation("{Count} episode updates to process", queuedEpisodeUpdates.Count);
-                    await ProcessQueuedEpisodeEvents(queuedEpisodeUpdates, traktUser, EventType.Add).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No episode updates to process");
-                }
+                await ProcessQueuedEpisodeEvents(queuedEpisodeDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
+                await ProcessQueuedEpisodeEvents(queuedEpisodeAdds, traktUser, EventType.Add).ConfigureAwait(false);
+                await ProcessQueuedEpisodeEvents(queuedEpisodeUpdates, traktUser, EventType.Add).ConfigureAwait(false);
 
-                if (queuedShowDeletes.Any())
-                {
-                    _logger.LogInformation("{Count} series deletions to process", queuedMovieDeletes.Count);
-                    await ProcessQueuedShowEvents(queuedShowDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No series deletions to process");
-                }
-
-                if (queuedShowAdds.Any())
-                {
-                    _logger.LogInformation("{Count} series additions to process", queuedShowAdds.Count);
-                    await ProcessQueuedShowEvents(queuedShowAdds, traktUser, EventType.Remove).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No series additions to process");
-                }
-
-                if (queuedShowUpdates.Any())
-                {
-                    _logger.LogInformation("{Count} series updates to process", queuedShowUpdates.Count);
-                    await ProcessQueuedShowEvents(queuedShowUpdates, traktUser, EventType.Remove).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No series updates to process");
-                }
+                await ProcessQueuedShowEvents(queuedShowDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
+                await ProcessQueuedShowEvents(queuedShowAdds, traktUser, EventType.Remove).ConfigureAwait(false);
+                await ProcessQueuedShowEvents(queuedShowUpdates, traktUser, EventType.Remove).ConfigureAwait(false);
             }
 
             // Everything is processed. Reset the event list.
             _queuedEvents.Clear();
         }
 
-        private async Task ProcessQueuedShowEvents(IEnumerable<LibraryEvent> events, TraktUser traktUser, EventType eventType)
+        private async Task ProcessQueuedShowEvents(IReadOnlyCollection<LibraryEvent> events, TraktUser traktUser, EventType eventType)
         {
+            if (events.Count == 0)
+            {
+                _logger.LogInformation("No shows with event type {EventType} to process", eventType);
+                return;
+            }
+
+            _logger.LogInformation("Processing {Count} shows with event type {EventType}", events.Count, eventType);
+
             var shows = events.Select(lev => (Series)lev.Item)
                 .Where(lev => !string.IsNullOrEmpty(lev.Name)
                     && (!string.IsNullOrEmpty(lev.GetProviderId(MetadataProvider.Tmdb))
@@ -299,8 +214,16 @@
         /// <param name="traktUser">The <see cref="TraktUser"/>.</param>
         /// <param name="eventType">The <see cref="EventType"/>.</param>
         /// <returns>Task.</returns>
-        private async Task ProcessQueuedMovieEvents(IEnumerable<LibraryEvent> events, TraktUser traktUser, EventType eventType)
+        private async Task ProcessQueuedMovieEvents(IReadOnlyCollection<LibraryEvent> events, TraktUser traktUser, EventType eventType)
         {
+            if (events.Count == 0)
+            {
+                _logger.LogInformation("No movies with event type {EventType} to process", eventType);
+                return;
+            }
+
+            _logger.LogInformation("Processing {Count} movies with event type {EventType}", events.Count, eventType);
+
             var movies = events.Select(lev => (Movie)lev.Item)
                 .Where(lev => !string.IsNullOrEmpty(lev.Name)
                     && (!string.IsNullOrEmpty(lev.GetProviderId(MetadataProvider.Tmdb))
@@ -325,8 +248,16 @@
         /// <param name="traktUser">The <see cref="TraktUser"/>.</param>
         /// <param name="eventType">The <see cref="EventType"/>.</param>
         /// <returns>Task.</returns>
-        private async Task ProcessQueuedEpisodeEvents(IEnumerable<LibraryEvent> events, TraktUser traktUser, EventType eventType)
+        private async Task ProcessQueuedEpisodeEvents(IReadOnlyCollection<LibraryEvent> events, TraktUser traktUser, EventType eventType)
         {
+            if (events.Count == 0)
+            {
+                _logger.LogInformation("No episode {EventType} to process", eventType);
+                return;
+            }
+
+            _logger.LogInformation("Processing {Count} episodes with event type {EventType}", events.Count, eventType);
+
             var episodes = events.Select(lev => (Episode)lev.Item)
                 .Where(lev => lev.Series != null
                     && !string.IsNullOrEmpty(lev.Series.Name)

File: Trakt/ScheduledTasks/SyncLibraryTask.cs [hunk 17]
```diff
@@ -163,40 +183,43 @@ public async Task ExecuteAsync(IProgress<double> progress, CancellationToken can
                 baseQuery.Limit = Limit;
                 baseQuery.StartIndex = offset;
 
-                var libraryMovies = _libraryManager.GetItemList(baseQuery);
+                var libraryMovies = _libraryManager.GetItemList(baseQuery)
+                    .OfType<Movie>()
+                    .Where(item => !traktUser.LocationsExcluded.Any(directory => item.Path.Contains(directory, StringComparison.OrdinalIgnoreCase)))
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncLibraryTask.cs:188]: If this completely filters the query result any future items won't be processed

File: Trakt/ScheduledTasks/SyncLibraryTask.cs [hunk 18]
```diff
@@ -385,140 +465,218 @@ public async Task ExecuteAsync(IProgress<double> progress, CancellationToken can
...
-                    _logger.LogError(e, "Exception handled sending episodes to trakt.tv");
+                    _logger.LogError(e, "Error updating episode play states");
                 }
-
-                progress.Report(100);
             }
         }
 
-        private void LogTraktResponseDataContract(TraktSyncResponse dataContract)
+        private void LogTraktResponseDataContract(IEnumerable<TraktSyncResponse> dataContracts, TraktItemType type)
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncLibraryTask.cs:628]:
```suggestion
        private void LogTraktResponseDataContract(IReadOnlyCollection<TraktSyncResponse> dataContracts, TraktItemType type)
```

I prefer to avoid `IEnumerable` when possible

File: Trakt/ScheduledTasks/SyncLibraryTask.cs [hunk 19]
```diff
@@ -385,140 +465,218 @@ public async Task ExecuteAsync(IProgress<double> progress, CancellationToken can
...
         {
-            _logger.LogDebug("TraktResponse Added Movies: {Count}", dataContract.Added.Movies);
-            _logger.LogDebug("TraktResponse Added Shows: {Count}", dataContract.Added.Shows);
-            _logger.LogDebug("TraktResponse Added Seasons: {Count}", dataContract.Added.Seasons);
-            _logger.LogDebug("TraktResponse Added Episodes: {Count}", dataContract.Added.Episodes);
-            foreach (var traktMovie in dataContract.NotFound.Movies)
+            if (dataContracts.Any())
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncLibraryTask.cs:630]:
```suggestion
            if (dataContracts.Count != 0)
```

File: Trakt/ScheduledTasks/SyncLibraryTask.cs [hunk 20]
```diff
@@ -385,140 +465,218 @@ public async Task ExecuteAsync(IProgress<double> progress, CancellationToken can
...
             {
-                _logger.LogError("TraktResponse not Found: {@TraktMovie}", traktMovie);
-            }
+                foreach (var dataContract in dataContracts)
+                {
+                    if (type is TraktItemType.movie)
+                    {
+                        if (dataContract.Added != null && dataContract.Added.Movies > 0)
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncLibraryTask.cs:636]:
```suggestion
                        if (dataContract.Added?.Movies > 0)
```

These can all be condensed

File: Trakt/ScheduledTasks/SyncLibraryTask.cs [hunk 21]
```diff
@@ -385,140 +465,218 @@ public async Task ExecuteAsync(IProgress<double> progress, CancellationToken can
...
-                                traktUser,
-                                collected ? EventType.Add : EventType.Remove,
-                                cancellationToken)
-                            .ConfigureAwait(false);
-                    if (dataContracts != null)
+                    var dataContracts = new List<TraktSyncResponse>();
+                    var percentPerRequest = availablePercent / (episodes.Count / 100.0);
+
+                    // Force update trakt.tv if we have more than 100 movies in the queue due to API
+                    while (episodes.Count > 100)
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncLibraryTask.cs:591]: This reduces the amount of lists created

```diff
Index: Trakt/ScheduledTasks/SyncLibraryTask.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Trakt/ScheduledTasks/SyncLibraryTask.cs b/Trakt/ScheduledTasks/SyncLibraryTask.cs
--- a/Trakt/ScheduledTasks/SyncLibraryTask.cs	(revision 73dc33dd88616b6f74bff4d99cce22a166dce405)
+++ b/Trakt/ScheduledTasks/SyncLibraryTask.cs	(date 1650586098241)
@@ -588,9 +588,10 @@
                     var percentPerRequest = availablePercent / (episodes.Count / 100.0);
 
                     // Force update trakt.tv if we have more than 100 movies in the queue due to API
-                    while (episodes.Count > 100)
+                    var offset = 0;
+                    while (offset < episodes.Count)
                     {
-                        var episodesToSend = episodes.Take(100).ToList();
+                        var episodesToSend = episodes.GetRange(offset, 100);
                         dataContracts = await _traktApi.SendEpisodePlaystateUpdates(
                             episodesToSend,
                             traktUser,
@@ -598,7 +599,7 @@
                             cancellationToken)
                         .ConfigureAwait(false);
 
-                        episodes.RemoveRange(0, 100);
+                        offset += 100;
                         currentProgress += percentPerRequest;
                         progress.Report(currentProgress);
 

```

Comment (cvium) [reply Trakt/ScheduledTasks/SyncLibraryTask.cs:591]: I don't think that's true. It will create a new list regardless, but GetRange is more efficient.

File: Trakt/ScheduledTasks/SyncLibraryTask.cs (hunk 17 above)
Comment (Shadowghost) [reply Trakt/ScheduledTasks/SyncLibraryTask.cs:188]: What exactly do you mean? The idea is to just sync the current state of the library, deletion, watched events are handled otherwise so it shouldn't be problematic if the data changes while syncing.

Comment (crobibero) [reply Trakt/ScheduledTasks/SyncLibraryTask.cs:199]: In the edge case where every item in the page is filtered out the loop will end without processing any further pages of items

Comment (Shadowghost) [reply Trakt/ScheduledTasks/SyncLibraryTask.cs:199]: Allright, I just ran into thius problem while fixing th eother task. Should be fixed in the next (way too large) commit.

File: Trakt/ServerMediator.cs [hunk 22]
```diff
@@ -145,7 +144,7 @@ private void LibraryManagerItemRemoved(object sender, ItemChangeEventArgs itemCh
         private void LibraryManagerItemAdded(object sender, ItemChangeEventArgs itemChangeEventArgs)
         {
             // Don't do anything if it's not a supported media type
-            if (!(itemChangeEventArgs.Item is Movie) && !(itemChangeEventArgs.Item is Episode) && !(itemChangeEventArgs.Item is Series))
+            if (itemChangeEventArgs.Item is not Movie && itemChangeEventArgs.Item is not Episode && itemChangeEventArgs.Item is not Series)
```
Comment (crobibero) [inline Trakt/ServerMediator.cs:147]:
```suggestion
            if (itemChangeEventArgs.Item is not Movie and not Episode and not Series)
```

File: Trakt/ServerMediator.cs [hunk 23]
```diff
@@ -158,6 +157,28 @@ private void LibraryManagerItemAdded(object sender, ItemChangeEventArgs itemChan
...
+        /// <summary>
+        /// Library item was updated.
+        /// Let trakt.tv know which item was updated in the user's library.
+        /// </summary>
+        /// <param name="sender">The sending entity.</param>
+        /// <param name="itemChangeEventArgs">The <see cref="ItemChangeEventArgs"/>.</param>
+        private void LibraryManagerItemUpdated(object sender, ItemChangeEventArgs itemChangeEventArgs)
+        {
+            // Don't do anything if it's not a supported media type
+            if (itemChangeEventArgs.Item is not Movie && itemChangeEventArgs.Item is not Episode && itemChangeEventArgs.Item is not Series)
```
Comment (crobibero) [inline Trakt/ServerMediator.cs:169]:
```suggestion
            if (itemChangeEventArgs.Item is not Movie and not Episode and not Series)
```

File: Trakt/Helpers/LibraryManagerEventsHelper.cs [hunk 24]
```diff
@@ -95,103 +101,105 @@ private async void OnQueueTimerCallback(object state)
...
-                    _logger.LogInformation("{Count} series deletions to process", queuedMovieDeletes.Count);
-                    await ProcessQueuedShowEvents(queuedShowDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
-                }
-                else
-                {
-                    _logger.LogInformation("No series deletions to process");
-                }
+                await ProcessQueuedShowEvents(queuedShowDeletes, traktUser, EventType.Remove).ConfigureAwait(false);
+                await ProcessQueuedShowEvents(queuedShowAdds, traktUser, EventType.Remove).ConfigureAwait(false);
+                await ProcessQueuedShowEvents(queuedShowUpdates, traktUser, EventType.Remove).ConfigureAwait(false);
```
Comment (crobibero) [inline Trakt/Helpers/LibraryManagerEventsHelper.cs:180]:
```suggestion
                await ProcessQueuedShowEvents(queuedShowAdds, traktUser, EventType.Add).ConfigureAwait(false);
                await ProcessQueuedShowEvents(queuedShowUpdates, traktUser, EventType.Update).ConfigureAwait(false);
```

File: Trakt/ScheduledTasks/SyncFromTraktTask.cs [hunk 25]
```diff
@@ -117,27 +113,48 @@ private async Task SyncTraktDataForUser(Jellyfin.Data.Entities.User user, double
...
+                 * In order to be as accurate as possible. We need to download the user's show collection and the user's watched shows.
                  * It's unfortunate that trakt.tv doesn't explicitly supply a bulk method to determine shows that have not been watched
                  * like they do for movies.
                  */
-                traktWatchedMovies = await _traktApi.SendGetAllWatchedMoviesRequest(traktUser).ConfigureAwait(false);
-                traktWatchedShows = await _traktApi.SendGetWatchedShowsRequest(traktUser).ConfigureAwait(false);
+                if (!(traktUser.SkipUnwatchedImportFromTrakt && traktUser.SkipWatchedImportFromTrakt))
+                {
+                traktWatchedMovies.AddRange(await _traktApi.SendGetAllWatchedMoviesRequest(traktUser).ConfigureAwait(false));
+                traktWatchedShows.AddRange(await _traktApi.SendGetWatchedShowsRequest(traktUser).ConfigureAwait(false));
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncFromTraktTask.cs:139]:
```suggestion
                    traktWatchedMovies.AddRange(await _traktApi.SendGetAllWatchedMoviesRequest(traktUser).ConfigureAwait(false));
                    traktWatchedShows.AddRange(await _traktApi.SendGetWatchedShowsRequest(traktUser).ConfigureAwait(false));
```

File: Trakt/ScheduledTasks/SyncFromTraktTask.cs [hunk 26]
```diff
@@ -155,61 +172,128 @@ private async Task SyncTraktDataForUser(Jellyfin.Data.Entities.User user, double
...
 
                 var mediaItems = _libraryManager.GetItemList(baseQuery);
+
                 previousCount = mediaItems.Count;
                 offset += Limit;
 
                 mediaItems = mediaItems.Where(i => _traktApi.CanSync(i, traktUser)).ToList();
 
-                foreach (var movie in mediaItems.OfType<Movie>())
+                if (mediaItems != null)
```
Comment (crobibero) [inline Trakt/ScheduledTasks/SyncFromTraktTask.cs:194]: `mediaItems` will never be `null` here

**Review by crobibero — APPROVED** [review]

**Comment by Shadowghost** [comment]
Please don't merge tonight, I'd like to do some more testing tomorrow just to be sure.

File: Trakt/Extensions.cs [hunk 27]
```diff
@@ -161,12 +175,12 @@ public static bool MetadataIsDifferent(this TraktMovieCollected collectedMovie,
...
-        /// Gets the ISO-8620 representation of a <see cref="DateTime"/>.
+        /// Gets the ISO-8601 representation of a <see cref="DateTime"/>.
         /// </summary>
-        /// <param name="dt">The <see cref="DateTime"/>.</param>
+        /// <param name="dateTime">The <see cref="DateTime"/>.</param>
         /// <returns>string.</returns>
-        public static string ToISO8601(this DateTime dt)
-            => dt.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);
+        public static string ToISO8601(this DateTime dateTime)
+            => dateTime.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'", CultureInfo.InvariantCulture);
```
Comment (cvium) [inline Trakt/Extensions.cs:183]: ToString("o") is equivalent btw

File: Trakt/Extensions.cs [hunk 28]
```diff
@@ -234,26 +248,181 @@ public static IList<IEnumerable<T>> ToChunks<T>(this IEnumerable<T> enumerable,
...
+        /// <param name="item">The <see cref="Episode"/>.</param>
+        /// <param name="episode">The <see cref="TraktEpisodeWatched"/>.</param>
+        /// <returns><see cref="bool"/> indicating if the <see cref="Episode"/> matches a <see cref="TraktEpisodeWatched"/>.</returns>
+        public static bool IsMatch(Episode item, TraktEpisodeWatched episode)
+        {
+            var episodeNumber = episode.Number;
+            var itemIndexNumber = item.IndexNumber;
+            var itemIndexNumberEnd = item.IndexNumberEnd;
+
+            return !itemIndexNumber.HasValue
```
Comment (cvium) [inline Trakt/Extensions.cs:421]: `Episode.ContainsEpisodeNumber(int number)` already does this

File: Trakt/Helpers/LibraryManagerEventsHelper.cs [hunk 29]
```diff
@@ -95,103 +101,115 @@ private async void OnQueueTimerCallback(object state)
         private async Task OnQueueTimerCallbackInternal()
         {
             _logger.LogInformation("Timer elapsed - processing queued items");
+            var queue = new List<LibraryEvent>();
```
Comment (cvium) [inline Trakt/Helpers/LibraryManagerEventsHelper.cs:104]: unused

File: Trakt/Helpers/UserDataManagerEventsHelper.cs (hunk 12 above)
Comment (cvium) [reply Trakt/Helpers/UserDataManagerEventsHelper.cs:121]: You can more or less remove the if-else by saving the MaxCount based on `userPackage.CurrentSeriesId != null`

File: Trakt/Helpers/LibraryManagerEventsHelper.cs (hunk 29 above)
Comment (Shadowghost) [reply Trakt/Helpers/LibraryManagerEventsHelper.cs:104]: I'll do a cleanup PR later to fix those things. Thanks for reviewing all the time.

File: Trakt/Extensions.cs (hunk 27 above)
Comment (Shadowghost) [reply Trakt/Extensions.cs:183]: Does `ToString("o")` really do `HH:mm:sssZ` and not `HH:mm:ssZ` ?

File: Trakt/Extensions.cs (hunk 28 above)
Comment (Shadowghost) [reply Trakt/Extensions.cs:421]: Nice, didn't know that. Seems like we can replace custom code in some other places too.

File: Trakt/Extensions.cs (hunk 27 above)
Comment (cvium) [reply Trakt/Extensions.cs:183]: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Roundtrip

File: Trakt/Helpers/LibraryManagerEventsHelper.cs (hunk 29 above)
Comment (cvium) [reply Trakt/Helpers/LibraryManagerEventsHelper.cs:104]: No, you immediately replace it `queue = _queuedEvents.ToList();`

Comment (Shadowghost) [reply Trakt/Helpers/LibraryManagerEventsHelper.cs:104]: So I could either do `AddRange` within the lock or don't inititialize with an empty list? According to VS Code I can't just do `var queue = _queuedEvents.ToList();` within the lock.

Comment (cvium) [reply Trakt/Helpers/LibraryManagerEventsHelper.cs:104]: Don't initialize
