### PR TITLE
Fix duplicate watched entries

### LINKED ISSUE #162: Duplicate plays bug auto remove
Every once in a while trakt add many views of the same episode or movie. Even the time is the same. So far I am using a python plugin to clean up duplicate plays but was wondering if the duplicate check can be added to the jellyfin plugin itself. If a episode is shown to be palyed 20-30 times at nine a clock then the plugin should remove those plays and keep 1 only.
Another request though that is not because of trakt bug I do not want a 2nd play of show or movie to be registered only the first play so removing all other plays after the first and not adding new plays if a movie is already shown as watched. This of course can be optional setting for users as some people might want to keep the data but for me only the first time I watched a movie is important not the repeat views so would prefer those plays not to be added.

### LINKED ISSUE #219: Jellyfin marking series episodes 2x
When I finish a series episode jellyfin marks the episode 2x. These two plays in Trakt are marked as watched at the same time. 

Is this issue a misconfiguration on my end or is this an issue with the plugin?

### PR DESCRIPTION
**Pull request by buthed010203**
Previously, a missing episode with a null id could be matched to another episode from the same chunk that had a null id which would result it in the episode being added to trakt twice.

The code isn't the most idiomatic as I just threw it together to get this fixed.

Fixes #162
Fixes #219

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

File: Trakt/Api/TraktApi.cs [hunk 1]
```diff
@@ -902,10 +902,10 @@ private List<Episode> FindNotFoundEpisodes(IEnumerable<Episode> episodeChunk, Tr
...
-                                                                         || episode.GetProviderId(MetadataProvider.TvRage) == traktEpisode.Ids.Tvrage?.ToString(CultureInfo.InvariantCulture));
+            var notFoundEpisode = episodeChunk.FirstOrDefault(episode => (!string.IsNullOrEmpty(episode.GetProviderId(MetadataProvider.Imdb)) && episode.GetProviderId(MetadataProvider.Imdb) == traktEpisode.Ids.Imdb)
+                                                                         || (!string.IsNullOrEmpty(episode.GetProviderId(MetadataProvider.Tmdb)) && episode.GetProviderId(MetadataProvider.Tmdb) == traktEpisode.Ids.Tmdb?.ToString(CultureInfo.InvariantCulture))
+                                                                         || (!string.IsNullOrEmpty(episode.GetProviderId(MetadataProvider.Tvdb)) && episode.GetProviderId(MetadataProvider.Tvdb) == traktEpisode.Ids.Tvdb?.ToString(CultureInfo.InvariantCulture))
+                                                                         || (!string.IsNullOrEmpty(episode.GetProviderId(MetadataProvider.TvRage)) && episode.GetProviderId(MetadataProvider.TvRage) == traktEpisode.Ids.Tvrage?.ToString(CultureInfo.InvariantCulture)));
```
Comment (crobibero) [inline Trakt/Api/TraktApi.cs:908]:
```suggestion
            var notFoundEpisode = episodeChunk.FirstOrDefault(episode =>
                (episode.TryGetProviderId(MetadataProvider.Imdb, out var imdbId)
                 && imdbId == traktEpisode.Ids.Imdb)
                || (episode.TryGetProviderId(MetadataProvider.Tmdb, out var tmdbId)
                    && tmdbId == traktEpisode.Ids.Tmdb?.ToString(CultureInfo.InvariantCulture))
                || (episode.TryGetProviderId(MetadataProvider.Tvdb, out var tvdbId)
                    && tvdbId == traktEpisode.Ids.Tvdb)
                || (episode.TryGetProviderId(MetadataProvider.TvRage, out var tvRageId)
                    && tvRageId == traktEpisode.Ids.Tvrage));
```

**Review by crobibero — APPROVED** [review]
