### PR TITLE
Broken method hotfix

### LINKED ISSUE #33: Does not sync anything on Jellyfin 10.5.0
I upgraded to latest JF nightly in order to get proper hw accelleration and noticed that the trakt.tv import just writes to the log that it finished running after 0 seconds. Checking back in my library no watched states were synced at all.
```
[2020-01-16 08:46:54.993 +01:00] [INF] Executing "Import playstates from Trakt.tv"
[2020-01-16 08:46:55.030 +01:00] [INF] "Import playstates from Trakt.tv" Completed after 0 minute(s) and 0 seconds
[2020-01-16 08:46:55.031 +01:00] [INF] ExecuteQueuedTasks
```

If I can debug this further it would be nice if someone could tell me how. I already enabled the logging feature in the plugin but actually there isn't anything additional being logged.

### PR DESCRIPTION
**Pull request by matthew-jones-uk**
Quick hotfix that closes #33 which causes the plugin to be broken on build 10.5.0. I haven't modified anything just removed some problematic lines of code.

### CODE REVIEW

**Comment by Bond-009** [comment]
This isn’t a fix, uncomment the code change the nuget package and min version to jellyfin 10.5. That should do the trick.

**Comment by matthew-jones-uk** [comment]
Much better!

File: Trakt/ScheduledTasks/SyncFromTraktTask.cs [hunk 1]
```diff
@@ -134,7 +134,7 @@ private async Task SyncTraktDataForUser(User user, double currentProgress, Cance
                         {
                             IncludeItemTypes = new[] { typeof(Movie).Name, typeof(Episode).Name },
                             IsVirtualItem = false,
-                            OrderBy = new[]
+                            OrderBy = new []
```
Comment (Bond-009) [inline Trakt/ScheduledTasks/SyncFromTraktTask.cs]: Remove the extra space
